### PR TITLE
Update for Tweakpane v4.

### PR DESCRIPTION
**Pull request by kitschpatrol**
Thanks for this plugin.

I ported it to Tweakpane 4.x. This is a breaking change for users of Tweakpane 3.x.

The updates were mostly based on the following documentation:

- https://cocopon.github.io/tweakpane/migration/v4/
- https://github.com/cocopon/tweakpane/issues/396#issuecomment-1418929095
- https://github.com/tweakpane/plugin-essentials/commit/be4394e25c9fe6744627f3a1e0b54f215b0fee60

### CODE REVIEW

**Comment by Simonoob** [comment]
can we get this merged? All new apps use Tweakpane 4.x

**Comment by kitschpatrol** [comment]
@Simonoob In case it helps in the meantime, I have the 4.x fork up on NPM here:

https://www.npmjs.com/package/@kitschpatrol/tweakpane-textarea-plugin

**Review by kgolinski — APPROVED** [review]
Great work!

**Comment by kgolinski** [comment]
Sorry for the delay. Merging now.

**Pull request merged**
